name: Obtener PUUID
on:
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run: pip install requests
      - name: Ejecutar script
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
        run: python get_puuid.py
